#!/bin/bash

# author: André Kelpe <efeshunderelf at googlemail.com
# licencse: Apache v2

# find out our region and yes, you can get this as csv file. How cool is that?
GEOIP_REGION=$(wget -qO- freegeoip.net/csv/ | tr '[A-Z]' '[a-z]' | tr -d '"'| awk -F, '{print $2}')


MIRRORLIST_FILE_NAME=$(mktemp)

# download the latest mirror list from apache. we ignore the last
# sync times and hope for the best...
wget -qO- http://www.apache.org/mirrors/mirrors.list | grep -v '^$' \
    | grep http | grep -v '^#' > $MIRRORLIST_FILE_NAME

# use US as the default region. apache does the same in their scripts...
REGION=us

# check if there is a mirror in our region
if grep -q " $GEOIP_REGION " $MIRRORLIST_FILE_NAME; then
    REGION=$GEOIP_REGION
fi

# finally download it all
wget $(grep " $REGION " $MIRRORLIST_FILE_NAME | shuf | head -1 | awk '{print $3}')/$*

# clean up after ourselves.
rm $MIRRORLIST_FILE_NAME
